# Generated by Django 2.2.4 on 2019-10-25 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('note', models.CharField(max_length=2047)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_commercial_user', models.BooleanField(default=False)),
                ('ad_consent_available', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_shot', models.CharField(max_length=511)),
                ('description_long', models.CharField(max_length=4095)),
                ('current_occupation', models.IntegerField(default=0)),
                ('max_occupation', models.IntegerField(default=0)),
                ('homepage', models.CharField(max_length=1023)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('no_of_people', models.IntegerField(default=1)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.Bonus')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Profile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Venue')),
            ],
        ),
    ]
