# Generated by Django 2.2.4 on 2019-10-26 17:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)])),
                ('city', models.CharField(max_length=127)),
                ('street', models.CharField(max_length=127)),
                ('house_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(max_length=2047)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Bonuses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_commercial_user', models.BooleanField(default=False)),
                ('ad_consent_available', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_short', models.CharField(max_length=511)),
                ('description_long', models.CharField(max_length=4095)),
                ('current_occupation', models.IntegerField(default=0)),
                ('max_occupation', models.IntegerField(default=0)),
                ('homepage', models.CharField(max_length=1023)),
                ('reservations_enabled', models.BooleanField(default=False)),
                ('real_time_queue_enabled', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('no_of_people', models.IntegerField(default=1)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.Bonus')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.Profile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Opening_Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10)),
                ('opening_morning', models.DateTimeField()),
                ('closing_morning', models.DateTimeField(blank=True, null=True)),
                ('opening_noon', models.DateTimeField(blank=True, null=True)),
                ('closing_noon', models.DateTimeField()),
                ('note', models.CharField(max_length=2047)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Venue')),
            ],
            options={
                'verbose_name': 'Opening Hours',
                'verbose_name_plural': 'Opening Hours',
            },
        ),
        migrations.CreateModel(
            name='Occupation_Past_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('occupation', models.IntegerField()),
                ('reservations', models.IntegerField()),
                ('reservations_total_people', models.IntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Venue')),
            ],
            options={
                'verbose_name': 'Occupation Past Data',
                'verbose_name_plural': 'Occupation Past Datas',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.Profile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Conditional_Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10)),
                ('note', models.CharField(max_length=2043)),
                ('trigger_occupation', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Venue')),
            ],
        ),
    ]
