# Generated by Django 2.2.4 on 2019-10-25 19:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.Profile'),
        ),
    ]
