# Generated by Django 2.2.4 on 2019-10-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20191026_0725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opening_Dates',
            new_name='Opening_Hours',
        ),
        migrations.AlterModelOptions(
            name='opening_hours',
            options={'verbose_name': 'Opening Hours', 'verbose_name_plural': 'Opening Hours'},
        ),
        migrations.CreateModel(
            name='Conditional_Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10)),
                ('note', models.CharField(max_length=2043)),
                ('trigger_occupation', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Venue')),
            ],
        ),
    ]
