# Generated by Django 2.2.4 on 2019-10-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20191026_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
