# Generated by Django 2.2.4 on 2019-10-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20191026_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
    ]
