# Generated by Django 2.2.4 on 2019-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20191026_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation_past_data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
