# Generated by Django 2.2.4 on 2019-10-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20191026_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation_past_data',
            name='reservations',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='occupation_past_data',
            name='reservations_total_people',
            field=models.IntegerField(default=-1),
        ),
    ]
